build:
  version: "3.0"

cards:
    message: "Welcome to FMCBank cards related local APIs "
    contactDetails:
      name: "RamCards - Developer"
      email: "RamCards@fmcbank.com"
    onCallSupport:
      - (412) 419-3491
      - (915) 382-1932