spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to FMCBank accounts related prod APIs "
  contactDetails:
    name: "RamProd - Product Owner"
    email: "RamProd@fmcbank.com"
  onCallSupport:
    - (617) 432-2356
    - (936) 564-8721