

build:
  version: "1.0"

cards:
  message: "Welcome to FMCBank accounts related prod APIs "
  contactDetails:
    name: "RamaccountsProd - Product Owner"
    email: "RamaccountsProd@fmcbank.com"
  onCallSupport:
    - (617) 432-2356
    - (936) 564-8721