
build:
  version: "2.0"

accounts:
  message: "Welcome to FMCBank accounts related qa APIs "
  contactDetails:
    name: "RamaccountsQA - Product Owner"
    email: "RAMaccountsQA@fmcbank.com"
  onCallSupport:
    - (617) 432-2356
    - (936) 564-8721