
build:
  version: "3.0"

accounts:
  message: "Welcome to FMCBank accounts related local APIs "
  contactDetails:
    name: "Ramlocal - Developer"
    email: "Ramlocal@fmcbank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
