build:
  version: "2.0"

cards:
  message: "Welcome to FMCBank cards related QA APIs "
  contactDetails:
    name: "RAMCardsQA - QA Lead"
    email: "RAMCardsQA@fmcbank.com"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267