build:
  version: "1.0"

cards:
  message: "Welcome to FmcBank cards related prod APIs "
  contactDetails:
    name: "RamCardsProd - Product Owner"
    email: "RamCardsProd@fmcbank.com"
  onCallSupport:
    - (617) 432-2356
    - (936) 564-8721