spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

loans:
  message: "Welcome to FmcBank cards related prod APIs "
  contactDetails:
    name: "RamLoansProd - Product Owner"
    email: "RamLoansProd@fmcbank.com"
  onCallSupport:
    - (617) 432-2356
    - (936) 564-8721